server:
    error:
        include-message: always
    port: 8080
spring:
    datasource:
        password: 12345
        url: jdbc:postgresql://localhost:5432/java10
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    jwt:
        secret_key: java-10
